### ISSUE TITLE
Fix: Remove Slack Status when vscode goes inactive

### ISSUE THREAD

**Issue by srzainab** [pullflow/vscode-pullflow#11]
https://www.figma.com/file/fmbq1JqhoP4J56hn7pX3Kc/Presence-redesign?type=whiteboard&node-id=0%3A1&t=u2JvUGYliIj43DcS-1

**Comment by zakmandhro** [comment]
Design:
Every ping for "flow state on" sets a timer to turn off, which gets overridden by next ping.

**Comment by srzainab** [comment]
Redesign: 
For each user, start/reset `setTimout` timer when flow state is received. If flow state is removed (status change is detected), clear the timer immediately, reset the slack status immediately. Set timer cb function to clear slack status (if flow state update is not received, timer will trigger the reset status)
