### ISSUE TITLE
Fix: Slack reminders text should link to PR thread

### ISSUE THREAD

**Issue by srzainab** [pullflow/vscode-pullflow#17]
Investigate if this can be done without losing the link to GitHub.

Current:

![Image](https://github.com/pullflow/vscode-pullflow/assets/83520846/455cdabc-e1c6-447a-9a7f-4fef6761f729)

Proposed: 

![Image](https://github.com/pullflow/vscode-pullflow/assets/83520846/1101cf98-3ae8-467f-a966-9dc8baa8775b)

**Comment by srzainab** [comment]
@zakmandhro @amna-pullflow thoughts on the `Discuss` link for Slack thread?

**Comment by zakmandhro** [comment]
The [Discuss] looks off because it is not a Slack convention. Perhaps we can make it more obvious using plain links.

> 🔄 Pull request 21: Update requirements.txt. [View in GitHub](#). [Discuss on Slack](#).

**Comment by srzainab** [comment]
Do we really need the `View in GitHub`? the PR is linked anyway - similar to how we show it everywhere else in PF (dashboard, channel, etc)

**Comment by srzainab** [comment]
The fix is on core side; tracking the issue here.
