### ISSUE TITLE
Fix: Shows empty quickpick when no pending PR tasks

### ISSUE THREAD

**Issue by zakmandhro** [pullflow/vscode-pullflow#32]
Screenshot:
<img width="400" alt="image" src="https://github.com/pullflow/vscode-pullflow/assets/15746/ca337428-3021-4264-befc-9f3eb3ed3d19">

Solutions:
1. It could show a link to the GitHub page or connected Slack channel of the current repo.

**Comment by hassan-pullflow** [comment]
![Image](https://github.com/pullflow/vscode-pullflow/assets/110373493/50b3eba5-8e3c-4b8b-b909-4d9133bf0736)
