### ISSUE TITLE
Status bar should be updated after action taken

### ISSUE THREAD

**Issue by zakmandhro** [pullflow/vscode-pullflow#34]
As soon as you take an action, e.g. 'request review', and the API call is complete, the status bar should be refreshed. Otherwise, it's immediately out of sync.

<img width="512" alt="image" src="https://github.com/pullflow/vscode-pullflow/assets/15746/29317785-0b02-4013-895f-1a6e698d3f97">

**Comment by srzainab** [comment]
on API success, setTimeout for 2 or 3 seconds to refresh the status bar PRs
