### ISSUE TITLE
Update VSCode Extensions to support Telemetry

### ISSUE THREAD

**Issue by srzainab** [pullflow/vscode-pullflow#50]
- [x] Update Readme
- [x] Create extension settings to disable telemetry (on by default)
- [x] Update VS Code telemetry settings through extension

**Comment by hassan-pullflow** [comment]
![Image](https://github.com/pullflow/vscode-pullflow/assets/110373493/beff8729-f464-498c-b8bf-378e4267b486)

**Comment by rabia-pullflow** [comment]
> ![Image](https://private-user-images.githubusercontent.com/110373493/294897788-d143a56f-e809-4582-8dec-f9f2084a8aa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODc4NDAsIm5iZiI6MTcwNTM4NzU0MCwicGF0aCI6Ii8xMTAzNzM0OTMvMjk0ODk3Nzg4LWQxNDNhNTZmLWU4MDktNDU4Mi04ZGVjLWY5ZjIwODRhOGFhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwNjQ1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmFkZjkzMmM1ZTQyMTYyYzAxZjNhZDVkYjJjNjQ1ZGJhZDBjYWEzYjNmNDU4MzdhZDIwODIwZTIyMDYzNzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0WeRbKQ3WeAD6QWY3NybkW8pxJB4OJniJk9B43N5xU4)

[ ] I agree to enable telemetry for Pullflow to enhance product experience.
Important: Telemetry requires both this option and the VS Code telemetry setting to be enabled. If either is turned off, no telemetry data will be collected or sent.
